[build]
  publish = "dist/moodify"
  command = "npm run build:prod"
  base = "moodify"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  # signed = "API_JWS_TOKEN"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


