[build]
  publish = "dist/moodify"
  command = "npm run build:prod"
  base = "moodify"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files  = ["/netlify/utils/*"]