[build]
  publish = "dist/moodify"
  command = "npm run build:prod"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
  path = '/categories.json'
  function = 'categories.json'

[[edge_functions]]
  path = '/audios.json'
  function = 'audios.json'